In [59]:
from utils import TravellingSalesmanProblem
import googlemaps
import numpy as np

In [60]:
city_names = ["Nis, Serbia","Kraljevo, Serbia","Jagodina, Serbia","Novi Sad, Serbia","Cacak, Serbia",  "Babusnica, Serbia", "Dimitrovgrad, Serbia"]
gmaps = googlemaps.Client(key = 'AIzaSyD4nE1eqouTNUPqSkLogyZMmjWPkuTZtU4')

In [61]:
save_res = gmaps.distance_matrix( origins = city_names, destinations = city_names )

In [62]:
save_res

{'destination_addresses': ['Niš, Serbia',
  'Kraljevo, Serbia',
  'Jagodina, Serbia',
  'Novi Sad, Serbia',
  'Čačak, Serbia',
  'Babušnica, Serbia',
  'Dimitrovgrad, Serbia'],
 'origin_addresses': ['Niš, Serbia',
  'Kraljevo, Serbia',
  'Jagodina, Serbia',
  'Novi Sad, Serbia',
  'Čačak, Serbia',
  'Babušnica, Serbia',
  'Dimitrovgrad, Serbia'],
 'rows': [{'elements': [{'distance': {'text': '1 m', 'value': 0},
     'duration': {'text': '1 min', 'value': 0},
     'status': 'OK'},
    {'distance': {'text': '147 km', 'value': 146735},
     'duration': {'text': '2 hours 8 mins', 'value': 7697},
     'status': 'OK'},
    {'distance': {'text': '106 km', 'value': 105831},
     'duration': {'text': '1 hour 9 mins', 'value': 4131},
     'status': 'OK'},
    {'distance': {'text': '336 km', 'value': 336277},
     'duration': {'text': '3 hours 28 mins', 'value': 12506},
     'status': 'OK'},
    {'distance': {'text': '206 km', 'value': 205529},
     'duration': {'text': '2 hours 39 mins', 'value'

Get the matrix

In [63]:
def get_distance_matrix(save_res):
    distance_matrix = np.zeros((len(city_names),len(city_names)))dd
    for i in range(len(city_names)):
        for j in range(len(city_names)):
            distance_matrix[i][j] = save_res['ddrows'][i]['elements'][j]['distance']['value']

In [64]:
distance_matrix``dd`

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [66]:
distance_matrix

array([[     0., 146735., 105831., 336277., 205529.,  67588., 104620.],
       [145674.,      0., 103182., 248422.,  37097., 208771., 245803.],
       [105263., 104544.,      0., 237204., 106456., 168359., 205392.],
       [336489., 247988., 236786.,      0., 220940., 399586., 436618.],
       [205331.,  36305., 105628., 220781.,      0., 268427., 305460.],
       [ 67488., 210047., 169143., 399588., 268841.,      0.,  51187.],
       [103958., 246516., 205612., 436058., 305310.,  50457.,      0.]])

In [67]:
list(distance_matrix)

[array([     0., 146735., 105831., 336277., 205529.,  67588., 104620.]),
 array([145674.,      0., 103182., 248422.,  37097., 208771., 245803.]),
 array([105263., 104544.,      0., 237204., 106456., 168359., 205392.]),
 array([336489., 247988., 236786.,      0., 220940., 399586., 436618.]),
 array([205331.,  36305., 105628., 220781.,      0., 268427., 305460.]),
 array([ 67488., 210047., 169143., 399588., 268841.,      0.,  51187.]),
 array([103958., 246516., 205612., 436058., 305310.,  50457.,      0.])]

In [68]:
start_city = 0
tour = TravellingSalesmanProblem(distance_matrix, start_city)
tour.solve()

In [69]:
print("Shortest path :", tour.shortest_path)

Shortest path : [0, 5, 6, 2, 1, 4, 3]


In [70]:
print("Minimum path cost :", tour.min_path_cost)

Minimum path cost : 686642.0


In [71]:
for i in range(len(city_names)):
    print(city_names[tour.shortest_path[i]].split(',')[0], end=" ")

Nis Babusnica Dimitrovgrad Jagodina Kraljevo Cacak Novi Sad 

In [75]:
np.save("distance_matrix",distance_matrix)